### ISSUE TITLE
Favor functional composition over trait decoration.

### ISSUE THREAD

**Issue by rockymadden** [rockymadden/stringmetric#17]

**Comment by ryanlecompte** [comment]
Can you give a small example of what you are aiming for here? Just curious. :-)

**Comment by rockymadden** [comment]
Sure, you can see a rough idea on this other project: https://github.com/rockymadden/delimited#transform-usage

There are a lot of areas in this older library that could be tightened up with functional programming concepts, this being one of them. With functional composition and higher order functions, rather than decorations, algorithms and metrics could be objects rather than classes, devs could provide their own rather than waiting on me to do something, etc. Hope that makes sense. More information, though not directly applicable: http://akisaarinen.fi/blog/2012/11/24/mismatch-between-oo-and-function-composition/

If it isn't desirable, let me know. I've just learned a lot about functional programming since developing this library and a lot of old cruft/OO ways of approaching problems I see now.

**Comment by ryanlecompte** [comment]
Awesome, I think that's a wonderful approach and I have done similar things myself in the past. Thanks!
