### ISSUE TITLE
Maven dependency mixup

### ISSUE THREAD

**Issue by maxthomas** [rockymadden/stringmetric#3]
Here's an easy one - the maven groupId / artifactId on the readme seem to be mixed up. 

Via readme: 
artifactId: com.rockymadden.stringmetric
groupId: stringmetric-core

Should read: 
groupId: com.rockymadden.stringmetric
artifactId: stringmetric-core

edits - formatting messed up

**Comment by rockymadden** [comment]
I see it. You think I would have earlier looking at it so often. ;)

Really appreciate the find. I am fixing it now.
