### ISSUE TITLE
cross Compile with Scala 2.9.2

### ISSUE THREAD

**Issue by MansurAshraf** [rockymadden/stringmetric#4]
Is it possible that you could cross compile this library with Scala 2.9.2? I am stuck on Scala 2.9.2 for foreseeable future and hence on a really old version of String Metric. 

I would really appreciate it if you could backport it 2.9.2

Thanks

**Comment by rockymadden** [comment]
Let me look into how other projects are doing this. I imagine via branches. I simply didn't do it because it was a bit of a pain ;)
